# Generated by Django 5.1.7 on 2025-03-14 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_product_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="thumnbail",
            new_name="thumbnail",
        ),
    ]
